version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db # this is a container name
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - 3306:3306
    networks:
      - custommer-app-db-network
    expose:
      - 3306

  web:
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate && python manage.py runserver localhost:8000"
    env_file:
      - .env
    environment:
      DB_HOST: mysql_db
    ports:
      - 8000:8000
    networks:
      - custommer-app-db-network
    depends_on:
      - db

networks:
  custommer-app-db-network:
