# Generated by Django 4.1.3 on 2022-11-21 12:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restaurant.restaurantApp.user.employee.models
import restaurant.restaurantApp.user.restaurant_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_voted",
                    models.DateField(default=datetime.date(1, 1, 1), null=True),
                ),
            ],
            options={
                "db_table": "auth_user_employee",
                "ordering": ["-id"],
                "default_related_name": "employee",
            },
            bases=("auth.user",),
            managers=[
                (
                    "objects",
                    restaurant.restaurantApp.user.employee.models.EmployeeManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
            ],
            options={"db_table": "menus", "ordering": ["-id"],},
        ),
        migrations.CreateModel(
            name="RestaurantWorker",
            fields=[],
            options={
                "ordering": ["-id"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                (
                    "objects",
                    restaurant.restaurantApp.user.restaurant_manager.models.RestaurantWorkerManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3")], max_length=20
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="restaurantApp.menu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="restaurantApp.employee",
                    ),
                ),
            ],
            options={"db_table": "votes",},
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restaurants",
                        to="restaurantApp.restaurantworker",
                    ),
                ),
            ],
            options={"db_table": "restaurants", "ordering": ["-id"],},
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(default="", max_length=4095)),
                ("price", models.FloatField()),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="restaurantApp.menu",
                    ),
                ),
            ],
            options={"db_table": "menu_items", "ordering": ["-id"],},
        ),
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="restaurantApp.restaurant",
            ),
        ),
    ]
